package com.tripnest.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity mapping public.profiles.
 *
 * The profiles table is created by supabase_setup.sql and has a FK:
 *   id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE
 *
 * We do NOT map auth.users as a JPA entity. The id field is treated
 * as a plain UUID primary key that happens to match auth.users.id.
 *
 * DDL (from supabase_setup.sql):
 *   id            UUID PRIMARY KEY
 *   full_name     TEXT NOT NULL DEFAULT ''
 *   email         TEXT NOT NULL DEFAULT ''
 *   profile_photo TEXT (nullable)
 *   bio           TEXT (nullable)
 *   role          TEXT NOT NULL DEFAULT 'USER'
 *   created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
 *
 * NOTE: travel_interests column does NOT exist in the actual schema.
 */
@Entity
@Table(name = "profiles", schema = "public")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Profile {

    /**
     * Profile ID — matches auth.users(id) exactly.
     * Not auto-generated by Hibernate; set by the Supabase trigger on user creation.
     */
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "full_name", nullable = false)
    private String fullName;

    @Column(name = "email", nullable = false)
    private String email;

    /** Supabase Storage URL for the profile photo. Nullable. */
    @Column(name = "profile_photo")
    private String profilePhoto;

    @Column(name = "bio", columnDefinition = "TEXT")
    private String bio;

    /**
     * Role — either 'USER' or 'ADMIN'.
     * The CHECK constraint is enforced at the DB level; we do not replicate it here.
     */
    @Column(name = "role", nullable = false)
    private String role;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;
}
